version: "3"
services:
  
  php:
    image: "phpa:latest"
    ports:
      - "80:80"
    container_name: lemp_php2_apache
    volumes:
      - ./html:/var/www/html
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: "mariadb:latest"
    ports:
        - "3277:3277"
        - "3306:3306"
    container_name: lemp_mariadb 
    environment:
      - MYSQL_ROOT_PASSWORD=romn2011.
      - MYSQL_DATABASE=lemp
    networks:
      - frontend
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: lemp_adminer
    networks:
      - frontend
    deploy:
     replicas: 4
     update_config:
       parallelism: 2
       delay: 10s
     restart_policy:
      condition: on-failure


networks:
  frontend:
  backend:


    
